<div class="sct-cleanup-left sct-export-left">
    <h3 style="margin-top: 0;"><?php _e("Export Plugin Settings", "smart-cleanup-tools"); ?></h3>
    <p style="min-height: 152px;">
        <?php _e("Plugin settings (one or more records stored in the WordPress options table) and scheduled jobs will be exported as serialized string and saved into text file that can be imported on this or any other WordPress installation. Do not make any modifications to this file, or later import will fail!", "smart-cleanup-tools"); ?>
        <br/>
        <label for="export_jobs"><input checked="checked" style="margin-top: 3px !important;" class="sct-checkbox" type="checkbox" id="export_jobs" name="export_jobs" /> <?php _e("Export Scheduled Jobs", "smart-cleanup-tools"); ?></label>
        <br/>
        <label for="export_settings"><input checked="checked" style="margin-top: 3px !important;" class="sct-checkbox" type="checkbox" id="export_settings" name="export_settings" /> <?php _e("Export Plugin Settings", "smart-cleanup-tools"); ?></label>
    </p>
    <input id="run-export" data-url="<?php echo SCT_URL; ?>core/export.php?_xport_scope=<?php echo $scope; ?>&_ajax_nonce=<?php echo wp_create_nonce('sct-settings-export'); ?>" type="button" class="button-primary" value="<?php _e("Export", "smart-cleanup-tools"); ?>" />
</div>
<div class="sct-cleanup-right sct-import-right">
    <form method="post" action="" enctype="multipart/form-data">
        <?php settings_fields('smart-cleanup-tools-import'); ?>

        <h3 style="margin-top: 0;"><?php _e("Import Plugin Settings", "smart-cleanup-tools"); ?></h3>
        <p style="min-height: 152px;">
            <?php _e("You need valid, unmodified export file (with .sct extension), generated by the export tool on this page.", "smart-cleanup-tools"); ?> 
            <?php _e("Importing scheduled jobs will only add jobs, all previous jobs will be unaffected.", "smart-cleanup-tools"); ?>

            <input class="sct-import-file" type="file" name="import_file" />
            <br/>
            <label for="import_jobs"><input checked="checked" style="margin-top: 3px !important;" class="sct-checkbox" type="checkbox" id="import_jobs" name="import_jobs" /> <?php _e("Import Scheduled Jobs", "smart-cleanup-tools"); ?></label>
            <br/>
            <label for="import_settings"><input checked="checked" style="margin-top: 3px !important;" class="sct-checkbox" type="checkbox" id="import_settings" name="import_settings" /> <?php _e("Import Plugin Settings", "smart-cleanup-tools"); ?></label>
        </p>
        <input type="submit" class="button-primary" value="<?php _e("Import", "smart-cleanup-tools"); ?>" />
    </form>
</div>
